### ISSUE TITLE
No ARM64 support for Fabric images

### ISSUE THREAD

**Issue by arturmartins** [hyperledger/firefly-cli#305] opened 2024-06-08 17:42 UTC
I just learned that there is no ARM64 support:
https://github.com/hyperledger/firefly-cli/blob/9c8b5dd279cb524a56f79d2b732fb399ee0cb541/internal/blockchain/fabric/fabric_provider.go#L621

It would be important to have a document explaining why. Furthermore, it would be greatly appreciated if there was an explanation of how it could be done locally (build your own images).

**Comment by EnriqueL8** [comment] 2024-06-17 11:01
I think it was the case that Fabric did not have ARM64 images but it seems that it has changed! https://lists.hyperledger.org/g/fabric/topic/96571575?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3A%2C%2C%2C0%2C0%2C0%2C96571575 

This would be a great contribution to make, marking as good first issue 😃

**Comment by EnriqueL8** [comment] 2024-07-17 13:05
For anyone looking at contributing a fix for this , I've just come across the same problem for Tessera in this PR https://github.com/hyperledger/firefly-cli/pull/315 and most of the hard work can be taken from that PR.

This is a great first issue for anyone to pick up!

**Comment by EnriqueL8** [comment] 2024-08-13 17:15
@dwertent found out that actually the v1.3.1 FF already has bumped the version to 2.5 of Fabric which has an ARM64 image in DockerHub, so the issue is obsolete

**Closed by EnriqueL8** 2024-08-13 17:15 UTC
Labels: good first issue, help wanted
